version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: "web-shop" # Имя БД, которое будет создано
      MYSQL_USER: "user" # Имя пользователя БД
      MYSQL_PASSWORD: "password" # Пароль пользователя БД
      MYSQL_ROOT_PASSWORD: "rootpassword" # Пароль пользователя root БД
    ports:
      - "3307:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d # Монтируем директорию с дампом
